package_creator: "briar-mills"
dataset_source: "UNHabitat"
owner_org: "unhabitat-das"
maintainer: "denmwa02"
data_update_frequency: "365"
license_id: "hdx-pddl"
caveats: "Read more at https://unhabitat.org/knowledge/data-and-analytics"
subnational: "1"
methodology: "Other"
methodology_other: "See methodology at https://data.unhabitat.org/pages/guidance"
private: False
