# Collector specific configuration
datasets:
  green_areas:
    base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/fbb02b19d417497093418484448e3465/data"
    country_header: "Country or Territory Name"
    date_header: "Data Reference Year"
    format: "xlsx"
    title: "Open spaces and green areas"
    notes: "Data on a) Average share of urban areas allocated to streets and open public spaces, and b) Share of urban population with convenient access to an open public space (defined as share of urban population within 400 meters walking distance along the street network to an open public space)."
    resource_notes: "SDG 11.7.1: Average share of the built-up area of cities that is open space for public use for all, by sex, age and persons with disabilities"
    filename: "SDG_11-7-1"

  urban_transport:
    base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/62b0629736c44068bcf4ce2cbce03f8f/data"
    country_header: "Country or Territory Name"
    date_header: "Data Reference Year"
    format: "xlsx"
    title: "Urban transport"
    notes: "Estimated share of urban population who can access a public transport stop within a walking distance of 500 meters (for low capacity public transport systems) and/or 1000 meters (for high capacity public transport systems) along the street network."
    resource_notes: "SDG 11.2.1: Proportion of population that has convenient access to public transport, by sex, age and persons with disabilities"
    filename: "SDG_11-2-1"

  urban_environment:
    base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/78f842544a734b3fade0c871387abaa9/data"
    header: 3
    country_header: "Country"
    date_min: 2015
    date_max: 2019
    format: "xls"
    title: "Urban environment and quality of life"
    notes: "Mean population exposure to particulate matter with a width of 2.5 microns or less in micrograms per cubic meter, presented by country and sub-national region levels. Data is per individual years in 2015, 2016, 2017, 2018 and 2019."
    resource_notes: "Air Quality: Mean Population Exposure to PM2.5 (Micrograms/m3), 2015 - 2019"
    filename: "Mean_Population_Exposure_to_PM2.5"

  spatial_growth_cities:
    base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/8df37ec6315449b185a8b080dee544ff/data"
    country_header: "Country or Territory Name"
    date_min: 1991
    date_max: 2023
    format: "xlsx"
    title: "Spatial growth of cities and urban areas"
    notes: "Multi-temporal city data on a) Annual land consumption rate (%), b) population growth rate (%), c) ratio of land consumption rate to population growth rate, and d) built up area per capita."
    resource_notes: "Global SDG 11.3.1 dataset"
    filename: "SDG_11-3-1"

  housing_slums:
    title: "Housing, slums and informal settlements"
    notes: "The share of urban population living in slum households per country and region, based on 4 out of 5 household shelter deprivations defined by UN-Habitat as indicators of informality: lack of access to improved water, lack of access to improved sanitation, lack of sufficient living area and quality/durability of structure. Security of tenure is the fifth deprivation that is not included due to data limitations."
    date_min: 2000
    date_max: 2020
    global: True
    resources:
      resource_1:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/db372d6e417d410ba6ee14be199e568b/data"
        format: "xlsx"
        resource_notes: "Proportion of Urban Population Living in Slum Households by Country or area 2000 - 2020 (Percent)"
        filename: "Slum_Estimates_2000-2020"

  basic_services:
    title: "Access to basic services in cities and urban areas"
    notes: "Proportion of population with access to various basic services including improved water services, improved sanitation facilities, clean energy for lighting, energy for cooking, internet connection, telephone network, solid waste management services and other basic services by city and urban area"
    date_min: 1990
    date_max: 2019
    global: True
    resources:
      resource_1:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/c0b23da0cd5442ad8ed4d3a4a0065524/data"
        format: "xlsx"
        resource_notes: "Population with Improved Water, Improved Sanitation and Other Urban Basic Services in Cities, Selected Countries (Percent)"
        filename: "Population_with_Improved_Water,_Improved_Sanitation_and_Other_Urban_Basic_Services_in_Cities,_Selected_Countries_(Percent)"
      resource_2:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/6e8ce4b4eda04f25b7a8af0e4281c950/data"
        format: "xlsx"
        resource_notes: "Population with Improved Water, Improved Sanitation and Other Urban Basic Services in Urban Areas, Selected Countries (Percent)"
        filename: "Population_with_Improved_Water,_Sanitation_and_Other_Urban_Basic_Services_in_Urban_Areas,_Selected_Countries_(Percent)"

  social_inclusion:
    title: "Social inclusion indicators"
    notes: "The share of urban population living in slum households per country and region, based on 4 out of 5 household shelter deprivations defined by UN-Habitat as indicators of informality: lack of access to improved water, lack of access to improved sanitation, lack of sufficient living area and quality/durability of structure. Security of tenure is the fifth deprivation that is not included due to data limitations. \nGini at disposable income after taxes and transfers by city or region per year between 2010 and 2017"
    date_min: 2000
    date_max: 2020
    global: True
    resources:
      resource_1:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/db372d6e417d410ba6ee14be199e568b/data"
        format: "xlsx"
        resource_notes: "Proportion of Urban Population Living in Slum Households by Country or area 2000 - 2020 (Percent)"
        filename: "Slum_Estimates_2000-2020"
      resource_2:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/9574109ff25c4ffcba778fc1e050a938/data"
        format: "xls"
        resource_notes: "Gini at disposable income after taxes and transfers"
        filename: "Gini_at_disposable_income_after_taxes_and_transfers,_2010_-_2017"

  economic_indicators:
    title: "Economic indicators"
    notes: "Economic indicators. See more at https://data.unhabitat.org/pages/economic-indicators"
    date_min: 2000
    date_max: 2017
    global: True
    resources:
      resource_1:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/9574109ff25c4ffcba778fc1e050a938/data"
        format: "xls"
        resource_notes: "Gini at disposable income after taxes and transfers"
        filename: "Gini_at_disposable_income_after_taxes_and_transfers,_2010_-_2017"
      resource_2:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/2e5ac6a26ff04816a4259dfa1276eea9/data"
        format: "xls"
        resource_notes: "GDP by Metropolitan Area, 2017"
        filename: "GDP_by_Metropolitan_Area,_2017"
      resource_3:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/0a84f38a6b9e4de793fe6a7adaeb6471/data"
        format: "xls"
        resource_notes: "GDP of metropolitan areas as a share of the national GDP, 2017"
        filename: "GDP_of_the_metropolitan_area_as_a_share_of_the_national_GDP,_2017"

  urban_population:
    title: "Urban population trends"
    notes: "Urban population trends. See more at https://data.unhabitat.org/pages/urban-population-and-demographic-trends"
    date_min: 1995
    date_max: 2050
    global: True
    resources:
      resource_1:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/c3b53897b73c434995e681b45f7182c3/data"
        format: "xlsx"
        resource_notes: "Urban Population at Mid-year by country 2000-2050 (Thousands)"
        filename: "Urban_Population_at_Mid-Year_by_Country,_2000-2050_(thousands)"
      resource_2:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/91b9244732a540af9e048887fbfacc27/data"
        format: "xlsx"
        resource_notes: "Percentage of Population at Mid-Year Residing in Urban areas by Country and Area, 2000-2050"
        filename: "Percentage_of_Population_at_Mid-Year_Residing_in_Urban_Country_and_Area,_2000-2050"
      resource_3:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/c425c4b45db846f4bf89fa5403ee68dd/data"
        format: "xlsx"
        resource_notes: "Average Annual Rate of Change of the Urban Population by Country 2000-2050 (Percent)"
        filename: "Average_Annual_Rate_of_Change_of_the_Urban_Population_by_Country,_2000-2050_(per_cent)"
      resource_4:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/beda0aca1ea74e93acae18cd23395773/data"
        format: "xlsx"
        resource_notes: "Average Annual Rate of Change of the Percentage Urban Population by Area 2000-2050 (Percent)"
        filename: "Average_Annual_Rate_of_Change_of_the_Percentage_Urban_by_Country,_2000-2050"
      resource_5:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/9ca4df2304ee457982eb04d7d19dbf11/data"
        format: "xlsx"
        resource_notes: "Population in Urban Agglomerations 2000 - 2035 (Thousands)"
        filename: "Population_in_Urban_Agglomerations"
      resource_6:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/f2f455c5ffc34e30a07fc05595aa6267/data"
        format: "xlsx"
        resource_notes: "Annual Rate of Population Change of Urban Agglomerations 1995 - 2035 (Percent)"
        filename: "Annual_Rate_of_Population_Change_of_Urban_Agglomerations"
      resource_7:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/1a20ea1831114ccda9ac74d4fb831d44/data"
        format: "xlsx"
        resource_notes: "Dependency Ratio - Youth by Country, 2015 - 2019 (Percent)"
        filename: "Dependency_Ratio_-_Youth_by_Country,_2015_-_2019_(Percent)"
      resource_8:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/91e78c795c2247f2be51564739c69daf/data"
        format: "xlsx"
        resource_notes: "Dependency Ratio - Elderly by Country, 2015 - 2019 (Percent)"
        filename: "Dependency_Ratio_-_Elderly_by_Country,_2015_-_2019_(Percent)"
      resource_9:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/c40b3b6d76c846d5856d06970df94bba/data"
        format: "xlsx"
        resource_notes: "Child Health Indicators"
        filename: "Child_Health_Indicators"
      resource_10:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/b536def3118649d4967242ab4cdbbd6d/data"
        format: "xlsx"
        resource_notes: "Child Nutrition Indicators"
        filename: "Child_Nutrition_indicators"
      resource_11:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/037450c9dc604055861e7a9cdcfa9690/data"
        format: "xlsx"
        resource_notes: "Child protection indicators"
        filename: "Child_protection_indicators"
      resource_12:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/ffac58cfa7b84320bbd203150ca118bc/data"
        format: "xlsx"
        resource_notes: "Children under 18 yrs living in slums households"
        filename: "Children_under_18_yrs_living_in_slums_households"
      resource_13:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/d51a6977f1e3483eae49919fe3caa439/data"
        format: "xlsx"
        resource_notes: "Maternal Health"
        filename: "Maternal_Health"
      resource_14:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/bade015e3ccc4c55bc289a64590df153/data"
        format: "xlsx"
        resource_notes: "Primary and Secondary Net Attendance Ratio"
        filename: "Primary_and_Secondary_Net_Attendance_Rate"
      resource_15:
        base_url: "https://guo-un-habitat.maps.arcgis.com/sharing/rest/content/items/2ef7eb5936bd4cc2b529e14e9616dd0c/data"
        format: "xlsx"
        resource_notes: "Under-5 mortality rate"
        filename: "Under-5_mortality_rate"

tags:
  - "urban"
  - "sustainable development goals-sdg"

countries:
  - AFG
  - BFA
  - CAF
  - CMR
  - COD
  - COL
  - ETH
  - GTM
  - HND
  - HTI
  - MLI
  - MMR
  - MOZ
  - NER
  - NGA
  - PSE
  - SDN
  - SLV
  - SOM
  - SSD
  - SYR
  - TCD
  - UKR
  - VEN
  - YEM